font_family      JetBrains Mono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

disable_ligatures never

cursor_shape beam
cursor_beam_thickness 1.5

cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0

cursor #599ba7
cursor_text_color background

window_padding_width 25

background_opacity 0.78

background #292a2b
foreground #eceff4

selection_background #696b6d
selection_foreground #ffffff

scrollback_lines 10000
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 1.0

shell fish --login
editor nvim

confirm_os_window_close 0

url_color #0087bd
url_style curly
open_url_with default


